var UI = require("ui");
var Settings = require("settings");
var Clay = require("clay");
var clayConfig = require("config");
var clay = new Clay(clayConfig, null, {autoHandleEvents: false});
var ajax = require("ajax");

var token = "";
var contacts = [];

var configPromptCard = new UI.Card({
    fullscreen: false,
    title: "Hello, DigiDuncan!",
    titleColor: "black"
});

var errorCard = new UI.Card({
    fullscreen: false,
    title: "Something went wrong:",
    subtitle: "Digi doesn't know JS!",
    titleColor: "black",
    backgroundColor: "yellow"
});

var loadingCard = new UI.Card({
    fullscreen: false,
    title: "Gettings contacts...",
    titleColor: "black"
});

var sendingMessageCard = new UI.Card({
    fullscreen: false,
    title: "Sending...",
    titleColor: "black",
    backgroundColor: "#aaaaaa"
});

var sentMessageCard = new UI.Card({
    fullscreen: false,
    title: "Message sent :)",
    titleColor: "black",
    backgroundColor: "#aaaaaa"
});

var contactsMenu = new UI.Menu({
    fullscreen:false,
    backgroundColor: "white",
    textColor: "black",
    highlightBackgroundColor: "liberty",
    highlightTextColor: "black"
});

var responsesMenu = new UI.Menu({
    fullscreen:false,
    backgroundColor: "white",
    textColor: "black",
    highlightBackgroundColor: "liberty",
    highlightTextColor: "black",
    sections: [
        {items: [
            {title: Settings.option("response1")},
            {title: Settings.option("response2")},
            {title: Settings.option("response3")}
        ]}
    ]
});

// eslint-disable-next-line no-unused-vars
Pebble.addEventListener("showConfiguration", async function(e) {
    Pebble.openURL(clay.generateUrl());
    console.log("showed settings");
});

function populateContactsMenu(arrayContacts){
    for(var i = 0; i < arrayContacts.length; i++){
        var contact = arrayContacts[i];

        var name = "";

        if(contact.name){
            name = contact.name;
        }
        else{
            var lastIndex = contact.recipients.length - 1;
            for(var j = 0; j < contact.recipients.length; j++){
                name += contact.recipients[j].username;
                if(j < lastIndex){
                    name += ", ";
                }
            }
        }

        if(contacts[i]) {
            contactsMenu.item(0, i, { title: name });
        }
    }
}

// eslint-disable-next-line no-unused-vars
function getContacts(arrayContacts, token){
    console.log("getting contacts");

    var ajaxURL = "https://discord.com/api/users/@me/channels";
    var ajaxHeaders = { "Authorization" : Settings.option("token")};
    var ajaxParams = { url: ajaxURL, type: "json", method: "get", headers: ajaxHeaders };

    ajax(ajaxParams, function(data){
        console.log("getting contacts succeeded!");
        contacts = data;

        // sort contacts based on who messaged last
        contacts.sort(function(a, b){
            //using last_message_id, we can derive time the last message was sent
            //as discord tokens are partially generated by timestamp
            var a_id = parseInt(a.last_message_id, 10);
            var b_id = parseInt(b.last_message_id, 10);
            return b_id - a_id;
        });

        Settings.data("contacts", contacts);

        populateContactsMenu(contacts);
        contactsMenu.show();
    }, function(data){
        console.log("getting contacts failed" + JSON.stringify(data) );
        errorCard.body = "" + data;
        errorCard.show();
    });
}

Pebble.addEventListener("webviewclosed", async function(e) {
    if (e && !e.response) {
        console.log(JSON.stringify(e, null, 4));
        return;
    }

    var dict = clay.getSettings(e.response);
    Settings.option(dict);
    Settings.option("token", Settings.option("token").replace(/['"]+/g, ""));
    console.log("set settings");
    console.log(Settings.option("response1"));

    getContacts(contacts, Settings.option("token"));
    loadingCard.show();
});

async function init() {
    contacts = Settings.data("contacts");
    token = Settings.option("token");

    if(token && contacts && contacts.length){
        populateContactsMenu(contacts);
        contactsMenu.show();
        configPromptCard.hide();
        errorCard.hide();
        loadingCard.hide();
    }
    else{
        configPromptCard.show();
    }
}
init();

var selectedContact;

contactsMenu.on("select", async function(selection){
    selectedContact = contacts[selection.itemIndex];
    responsesMenu.show();
});

responsesMenu.on("select", async function(selection){
    var message = selection.item.title;
    console.log(message);
    console.log("sending message");

    var ajaxURL = "https://discordapp.com/api/channels/" + selectedContact.id + "/messages";
    var ajaxHeaders = { "Authorization" : token };
    var ajaxData = { "content" : message };
    var ajaxParams = { url: ajaxURL, type: "json",
        method: "post", data: ajaxData, headers: ajaxHeaders };

    // eslint-disable-next-line no-unused-vars
    ajax(ajaxParams, function(data){
        console.log("message sent!");
        sentMessageCard.show();
    }, function(error){
        console.log("sending message failed" + JSON.stringify(error) );
        errorCard.body = "" + error;
        errorCard.show();
    });

    sendingMessageCard.show();
});

errorCard.on("show", async function(){
    loadingCard.hide();
    contactsMenu.hide();
    responsesMenu.hide();
    sendingMessageCard.hide();
});

loadingCard.on("show", async function(){
    configPromptCard.hide();
});

contactsMenu.on("show", async function(){
    loadingCard.hide();
});

sentMessageCard.on("show", async function(){
    contactsMenu.hide();
    responsesMenu.hide();
    sendingMessageCard.hide();

    setTimeout(() => {
        contactsMenu.show();
        sentMessageCard.hide();
    }, 1000);
});
