var ajaxsync = require("ajax");

async function ajax(params) {
    return new Promise(function(resolve, reject) {
        ajaxsync(params, resolve, reject);
    });
}

module.exports.getContacts = async function(token){
    console.log("getting contacts");

    var ajaxURL = "https://discord.com/api/users/@me/channels";
    var ajaxHeaders = { "Authorization" : token};
    var ajaxParams = { url: ajaxURL, type: "json", method: "get", headers: ajaxHeaders };

    try {
        var contacts = await ajax(ajaxParams);
    }
    catch (err) {
        console.error("getting contacts failed " + JSON.stringify(err));
        throw err;
    }
    console.log("getting contacts succeeded!");

    // sort contacts based on who messaged last
    contacts.sort(function(a, b){
        //using last_message_id, we can derive time the last message was sent
        //as discord tokens are partially generated by timestamp
        var a_id = parseInt(a.last_message_id, 10);
        var b_id = parseInt(b.last_message_id, 10);
        return b_id - a_id;
    });

    return contacts;
};

module.exports.sendMessage = async function sendMessage(contactId, message, token) {
    var ajaxURL = "https://discordapp.com/api/channels/" + contactId + "/messages";
    var ajaxHeaders = { "Authorization" : token };
    var ajaxData = { "content" : message };
    var ajaxParams = { url: ajaxURL, type: "json", method: "post", data: ajaxData, headers: ajaxHeaders };

    console.log("sending message");
    try {
        await ajax(ajaxParams);
    }
    catch (err) {
        console.log("sending message failed" + JSON.stringify(err) );
        throw err;
    }
    console.log("message sent!");
};
